"""Pydantic v2 models for MoodBoard AI."""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class SearchQuery(BaseModel):
    """A platform-specific search query generated by the LLM."""

    platform: str
    query_string: str
    style_hints: list[str]


class ImageResult(BaseModel):
    """A single image result with AI-generated tags and metadata."""

    id: str = Field(description="SHA-256 hex digest of the image URL")
    url: str
    thumbnail_url: str
    source_platform: str
    source_link: str
    title: str
    tags: list[str] = Field(default_factory=list)
    caption: str = ""
    color_palette: list[str] = Field(default_factory=list)
    style_label: str = ""
    mood: str = ""
    aspect_ratio: float = 1.0
    tagging_complete: bool = False


class WishlistCreate(BaseModel):
    """Payload for saving an image to a wishlist project."""

    project_name: str
    image_result: ImageResult
    notes: str = ""


class WishlistItem(BaseModel):
    """A wishlist item stored in the database."""

    id: str
    project_name: str
    image_result: ImageResult
    added_at: datetime
    notes: str = ""
